export const USER_REGISTER="USER_REGISTER"
export const USER_REGISTER_RESPONSE="USER_REGISTER_RESPONSE"
export const USER_REGISTER_ERROR="USER_REGISTER_ERROR"
export const CLEAN_UP_REGISTER="CLEAN_UP_REGISTER"

export const USER_LOGIN="USER_LOGIN"
export const USER_LOGIN_RESPONSE="USER_LOGIN_RESPONSE"
export const USER_LOGIN_ERROR="USER_LOGIN_ERROR"
export const CLEAN_UP_LOGIN="CLEAN_UP_LOGIN"

export const GET_USER="GET_USER"
export const GET_USER_RESPONSE="GET_USER_RESPONSE"
export const GET_USER_ERROR="GET_USER_ERROR"
export const CLEAR_USER="CLEAR_USER"

export const ORG_USERS="ORG_USERS"
export const ORG_USERS_RESPONSE="ORG_USERS_RESPONSE"
export const ORG_USERS_ERROR="ORG_USERS_ERROR"

export const UPDATE_ORG_ROLE="UPDATE_ORG_ROLE"
export const UPDATE_ORG_ROLE_RESPONSE="UPDATE_ORG_ROLE_RESPONSE"
export const UPDATE_ORG_ROLE_ERROR="UPDATE_ORG_ROLE_ERROR"

export const UPDATE_USER_METADATA="UPDATE_USER_METADATA"
export const UPDATE_USER_METADATA_RESPONSE="UPDATE_USER_METADATA_RESPONSE"
export const UPDATE_USER_METADATA_EROR="UPDATE_USER_METADATA_EROR"
export const CLEAN_UP_UPDATE="CLEAN_UP_UPDATE"

export const ADD_PRODUCT="ADD_PRODUCT"
export const ADD_PRODUCT_RESPONSE="ADD_PRODUCT_RESPONSE"
export const ADD_PRODUCT_ERROR="ADD_PRODUCT_ERROR"
export const CLEAN_UP_ADD_PRODUCT="CLEAN_UP_ADD_PRODUCT"

export const GET_ALL_PRODUCT="GET_ALL_PRODUCT"
export const GET_ALL_PRODUCT_RESPONSE="GET_ALL_PRODUCT_RESPONSE"
export const GET_ALL_PRODUCT_ERROR="GET_ALL_PRODUCT_ERROR"

export const BOOKING_PRODUCT="BOOKING_PRODUCT"
export const BOOKING_PRODUCT_RESPONSE="BOOKING_PRODUCT_RESPONSE"
export const BOOKING_PRODUCT_ERROR="BOOKING_PRODUCT_ERROR"
export const CLEAN_UP_BOOKING="CLEAN_UP_BOOKING"

export const GET_VENDOR_PLACE_ORDER_PRODUCT="GET_VENDOR_PLACE_ORDER_PRODUCT"
export const GET_VENDOR_PLACE_ORDER_PRODUCT_RESPONSE="GET_VENDOR_PLACE_ORDER_PRODUCT_RESPONSE"
export const GET_VENDOR_PLACE_ORDER_PRODUCT_ERROR="GET_VENDOR_PLACE_ORDER_PRODUCT_ERROR"

export const GET_ORDER_STATUS="GET_ORDER_STATUS"
export const GET_ORDER_STATUS_RESPONSE="GET_ORDER_STATUS_RESPONSE"
export const GET_ORDER_STATUS_ERROR="GET_ORDER_STATUS_ERROR"
export const CLEAN_UP__ORDER_STATUS = "CLEAN_UP__ORDER_STATUS"

export const GET_VENDOR_ORDER_LIST="GET_VENDOR_ORDER_LIST"
export const GET_VENDOR_ORDER_LIST_RESPONSE="GET_VENDOR_ORDER_LIST_RESPONSE"
export const GET_VENDOR_ORDER_LIST_ERROR="GET_VENDOR_ORDER_LIST_ERROR"
export const CLEAN_UP_VENDOR_ORDER_LIST="CLEAN_UP_VENDOR_ORDER_LIST"

export const UPDATE_ORDER_STATUS="UPDATE_ORDER_STATUS"
export const UPDATE_ORDER_STATUS_RESPONSE="UPDATE_ORDER_STATUS_RESPONSE"
export const UPDATE_ORDER_STATUS_ERROR="UPDATE_ORDER_STATUS_ERROR"
export const CLEAR_UPDATE_ORDER_STATUS="CLEAR_UPDATE_ORDER_STATUS"

export const GET_CUSTOMER_ORDER="GET_CUSTOMER_ORDER"
export const GET_CUSTOMER_ORDER_RESPONSE="GET_CUSTOMER_ORDER_RESPONSE"
export const GET_CUSTOMER_ORDER_ERROR="GET_CUSTOMER_ORDER_ERROR"

export const ORDER_PAYMENT="ORDER_PAYMENT"
export const ORDER_PAYMENT_RESPONSE="ORDER_PAYMENT_RESPONSE"
export const ORDER_PAYMENT_ERROR="ORDER_PAYMENT_ERROR"

export const GET_PAYMENT="GET_PAYMENT"
export const GET_PAYMENT_RESPONSE="GET_PAYMENT_RESPONSE"
export const GET_PAYMENT_ERROR="GET_PAYMENT_ERROR"
export const CLEAR_PAYMENT="CLEAR_PAYMENT"

export const GET_SINGLE_PRODUCT="GET_SINGLE_PRODUCT"
export const GET_SINGLE_PRODUCT_RESPONSE="GET_SINGLE_PRODUCT_RESPONSE"
export const GET_SINGLE_PRODUCT_ERROR="GET_SINGLE_PRODUCT_ERROR"
export const SINGLE_PRODUCT_CLEAN="SINGLE_PRODUCT_CLEAN"

export const GET_VENDOR_STOCK="GET_VENDOR_STOCK"
export const GET_VENDOR_STOCK_RESPONSE="GET_VENDOR_STOCK_RESPONSE"
export const GET_VENDOR_STOCK_ERROR="GET_VENDOR_STOCK_ERROR"

export const UPDATE_VENDOR_PRODUCT="UPDATE_VENDOR_PRODUCT"
export const UPDATE_VENDOR_PRODUCT_RESPONSE="UPDATE_VENDOR_PRODUCT_RESPONSE"
export const UPDATE_VENDOR_PRODUCT_ERROR="UPDATE_VENDOR_PRODUCT_ERROR"

export const DELETE_VENDOR_PRODUCT="DELETE_VENDOR_PRODUCT"
export const DELETE_VENDOR_PRODUCT_RESPONSE="DELETE_VENDOR_PRODUCT_RESPONSE"
export const DELETE_VENDOR_PRODUCT_ERROR="DELETE_VENDOR_PRODUCT_ERROR"

export const GET_ORDER_IN_RANGE="GET_ORDER_IN_RANGE"
export const GET_ORDER_IN_RANGE_RESPONSE="GET_ORDER_IN_RANGE_RESPONSE"
export const GET_ORDER_IN_RANGE_ERROR="GET_ORDER_IN_RANGE_ERROR"

export const CREATE_NOTIFICATION="CREATE_NOTIFICATION"
export const CREATE_NOTIFICATION_RESPONSE="CREATE_NOTIFICATION_RESPONSE"
export const CREATE_NOTIFICATION_ERROR="CREATE_NOTIFICATION_ERROR"

export const GET_NOTIFICATION="GET_NOTIFICATION"
export const GET_NOTIFICATION_RESPONSE="GET_NOTIFICATION_RESPONSE"
export const GET_NOTIFICATION_ERROR="GET_NOTIFICATION_ERROR"

export const DELETE_NOTIFICATION="DELETE_NOTIFICATION"
export const DELETE_NOTIFICATION_RESPONSE="DELETE_NOTIFICATION_RESPONSE"
export const DELETE_NOTIFICATION_ERROR="DELETE_NOTIFICATION_ERROR"
export const CLEAR_NOTIFICATION="CLEAR_NOTIFICATION"

export const GET_EARNING="GET_EARNING"
export const GET_EARNING_RESPONSE="GET_EARNING_RESPONSE"
export const GET_EARNING_ERROR="GET_EARNING_ERROR"

export const GET_ALL_AREA_PRODUCT="GET_ALL_AREA_PRODUCT"
export const GET_ALL_AREA_PRODUCT_RESPONSE="GET_ALL_AREA_PRODUCT_RESPONSE"
export const GET_ALL_AREA_PRODUCT_ERROR="GET_ALL_AREA_PRODUCT_ERROR"

export const FORGET_PASSWORD="FORGET_PASSWORD"
export const FORGET_PASSWORD_RESPONSE="FORGET_PASSWORD_RESPONSE"
export const FORGET_PASSWORD_ERROR="FORGET_PASSWORD_ERROR"