export const USER_LOGIN_STATUS = "USER_LOGIN_STATUS"
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

export const USER_REGISTER_STATUS="USER_REGISTER_STATUS"
export const USER_REGISTER_RESPONSE="USER_REGISTER_RESPONSE"
export const USER_REGISTER_ERROR="USER_REGISTER_ERROR"

export const FORGET_PASSWORD_STATUS="FORGET_PASSWORD_STATUS"
export const FORGET_PASSWORD_RESPONSE="FORGET_PASSWORD_RESPONSE"
export const FORGET_PASSWORD_ERROR="FORGET_PASSWORD_ERROR"

export const UPLOAD_PROPERTY_IMAGES_STATUS="UPLOAD_PROPERTY_IMAGES_STATUS"
export const UPLOAD_PROPERTY_IMAGES_RESPONSE="UPLOAD_PROPERTY_IMAGES_RESPONSE"
export const UPLOAD_PROPERTY_IMAGES_ERROR="UPLOAD_PROPERTY_IMAGES_ERROR"

export const UPLOAD_PRODUCT_STATUS="UPLOAD_PRODUCT_STATUS"
export const UPLOAD_PRODUCT_RESPONSE="UPLOAD_PRODUCT_RESPONSE"
export const UPLOAD_PRODUCT_ERROR="UPLOAD_PRODUCT_ERROR"
export const CLEAR_UPLOAD_PRODUCT_STORE="CLEAR_UPLOAD_PRODUCT_STORE"

export const GET_PRODUCT_LIST_STATUS="GET_PRODUCT_LIST_STATUS"
export const GET_PRODUCT_LIST_RESPONSE="GET_PRODUCT_LIST_RESPONSE"
export const GET_PRODUCT_LIST_ERROR="GET_PRODUCT_LIST_ERROR"

export const PLACE_BOOKING_STATUS="PLACE_BOOKING_STATUS"
export const PLACE_BOOKING_RESPONSE="PLACE_BOOKING_RESPONSE"
export const PLACE_BOOKING_ERROR="PLACE_BOOKING_ERROR"

export const RESET_FORGET_PASSWORD_RESPONSE="RESET_FORGET_PASSWORD_RESPONSE"