export const USER_LOGIN_STATUS = "USER_LOGIN_STATUS"
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

export const USER_REGISTER_STATUS="USER_REGISTER_STATUS"
export const USER_REGISTER_RESPONSE="USER_REGISTER_RESPONSE"
export const USER_REGISTER_ERROR="USER_REGISTER_ERROR"

export const FORGET_PASSWORD_STATUS="FORGET_PASSWORD_STATUS"
export const FORGET_PASSWORD_RESPONSE="FORGET_PASSWORD_RESPONSE"
export const FORGET_PASSWORD_ERROR="FORGET_PASSWORD_ERROR"

export const UPLOAD_PROPERTY_IMAGES_STATUS="UPLOAD_PROPERTY_IMAGES_STATUS"
export const UPLOAD_PROPERTY_IMAGES_RESPONSE="UPLOAD_PROPERTY_IMAGES_RESPONSE"
export const UPLOAD_PROPERTY_IMAGES_ERROR="UPLOAD_PROPERTY_IMAGES_ERROR"

export const RESET_FORGET_PASSWORD_RESPONSE="RESET_FORGET_PASSWORD_RESPONSE"